theme: jekyll-theme-minimal
title: OnDemandEnv Platform
description: Domain-Driven Design for Distributed Systems | A Contract-First Platform
logo: /assets/img/logo.png

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-sass-converter

sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules

collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "docs"
      type: "docs"
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
  - node_modules

github:
  is_project_page: true
  repository_url: https://github.com/ondemandenv/odmd-platform

google_analytics:

navigation:
  - title: Home
    url: /
  - title: Theory
    url: /docs/theory/overview
  - title: Implementation 
    url: /docs/implementations/aws/overview
  - title: About
    url: /docs/about