theme: jekyll-theme-minimal
title: OnDemandEnv Platform
description: Domain-Driven Design for Distributed Systems | A Contract-First Platform
logo: /assets/img/logo.png

url: https://garyy7811.github.io
baseurl: "/garyy7811"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-sass-converter

sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules

collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
  - node_modules

github:
  is_project_page: true
  repository_url: https://github.com/ondemandenv/odmd-platform

google_analytics:

navigation:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: About
    url: /about/