theme: jekyll-theme-minimal
title: Ondemandenv Platform
description: Simplifying Service-Oriented Architecture and Distributed Systems Development
logo: /assets/images/logo.png
show_downloads: false
google_analytics: UA-000000-01