theme: jekyll-theme-minimal
title: OnDemandEnv Platform
description: Domain-Driven Design for Distributed Systems
logo: /assets/images/logo.png
show_downloads: false
google_analytics: UA-000000-01
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
navigation:
  - title: Home
    url: /
  - title: Domain Theory
    url: /docs/theory
  - title: AWS Implementation
    url: /docs/implementations/aws
  - title: About
    url: /docs/about
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "docs/theory"
    values:
      layout: theory
  - scope:
      path: "docs/implementations"
    values:
      layout: implementation